-- ============================================================
-- SQL QUERIES FOR ONLINE RETAIL ANALYSIS
-- Generated by 02_sql_analysis.py
-- ============================================================

-- 1. Monthly revenue trend

SELECT 
    InvoiceYearMonth AS month,
    ROUND(SUM(TotalPrice), 2) AS revenue,
    COUNT(DISTINCT InvoiceNo) AS orders,
    ROUND(AVG(TotalPrice), 2) AS avg_order_value
FROM transactions
GROUP BY InvoiceYearMonth
ORDER BY month;


-- 2. Top 10 products by revenue

SELECT 
    StockCode,
    Description,
    ROUND(SUM(TotalPrice), 2) AS revenue,
    COUNT(DISTINCT InvoiceNo) AS order_count,
    SUM(Quantity) AS total_quantity
FROM transactions
GROUP BY StockCode, Description
ORDER BY revenue DESC
LIMIT 10;


-- 3. Revenue by country (excluding UK)

SELECT 
    Country,
    ROUND(SUM(TotalPrice), 2) AS revenue,
    COUNT(DISTINCT CustomerID) AS customers,
    COUNT(DISTINCT InvoiceNo) AS orders
FROM transactions
WHERE Country != 'United Kingdom'
GROUP BY Country
ORDER BY revenue DESC
LIMIT 10;


-- 4. Average order value

SELECT 
    ROUND(AVG(order_total), 2) AS avg_order_value
FROM (
    SELECT 
        InvoiceNo,
        SUM(TotalPrice) AS order_total
    FROM transactions
    GROUP BY InvoiceNo
);


-- 5. Repeat customer rate

WITH customer_orders AS (
    SELECT 
        CustomerID,
        COUNT(DISTINCT InvoiceNo) AS order_count
    FROM transactions
    GROUP BY CustomerID
)
SELECT 
    COUNT(CASE WHEN order_count > 1 THEN 1 END) AS repeat_customers,
    COUNT(*) AS total_customers,
    ROUND(100.0 * COUNT(CASE WHEN order_count > 1 THEN 1 END) / COUNT(*), 1) AS repeat_rate_pct
FROM customer_orders;


-- 6. Best day of week

SELECT 
    InvoiceDayOfWeek AS day,
    ROUND(SUM(TotalPrice), 2) AS revenue,
    COUNT(DISTINCT InvoiceNo) AS orders
FROM transactions
GROUP BY InvoiceDayOfWeek
ORDER BY revenue DESC;


-- 7. Top customers by lifetime spend

SELECT 
    CustomerID,
    ROUND(SUM(TotalPrice), 2) AS lifetime_value,
    COUNT(DISTINCT InvoiceNo) AS frequency,
    COUNT(*) AS total_items,
    MAX(InvoiceDate) AS last_purchase
FROM transactions
GROUP BY CustomerID
ORDER BY lifetime_value DESC
LIMIT 20;


-- 8. RFM components (for customer segmentation)

SELECT 
    CustomerID,
    JULIANDAY((SELECT MAX(InvoiceDate) FROM transactions)) - JULIANDAY(MAX(InvoiceDate)) AS recency_days,
    COUNT(DISTINCT InvoiceNo) AS frequency,
    ROUND(SUM(TotalPrice), 2) AS monetary
FROM transactions
GROUP BY CustomerID
ORDER BY monetary DESC;
